#UNA FABRICA DE INSTRUMENTOS MUSICALES POSEE UNA LISTA CON TODAS SUS SUCURSALES
#CADA SUCURSAL TIENE SU NOMBRE Y UNA LISTA CON TODOS LOS INSTRUMENTOS A LA VENTA
#DE CADA UNO DE ELLOS SE SABE SU ID ALFANUMERICO, SU PRECIO Y SU TIPO (PERCUSION, VIENTO, CUERDA)

#PUNTOS A DESARROLLAR
#1- DESARROLLAR EL DIAGRAMA DE CLASES UML QUE MODELE LO ENUNCIADO Y DONDE CONSTEN LAS CLASES CON SUS ATRIBUTOS METODOS Y RELACIONES (LOS CONSTRUCTORES PUEDEN OMITIRSE)
#2- CREAR UN PROYECTO EN PYTHON QUE RESUELVA:
#A) LA EXPLOTACION DEL METODO LISTAR INSTRUMENTOS QUE MUESTRE EN LA CONSOLA TODOS LOS DATOS DE CADA UNO DE LOS INSTRUMENTOS 
#B) LA EXPLOTACION DEL METODO INSTRUMENTOS POR TIPO QUE DEVUELVA UNA LISTA DE INSTRUMENTOS CUYO TIPO COINCIDA CON EL RECIBIDO POR PARAMETRO.
#C) LA EXPLOTACION DEL METODO BORRAR INSTRUMENTO QUE RECIBA UN ID Y ELIMINE EL INSTRUMENTO ASOCIADO A TAL ID DE LA SUCURSAL DONDE SE ENCUENTRE
#D) LA EXPLOTACION DEL METODO PORCINSTRUMENTOSPORTIPO QUE RECIBA EL NOMBBRE DE UNA SUCURSAL Y RETORNE LOS PORCENTAJES DE INSTRUMENTOS POR TIPO QUE HAY PARA TAL SUCURSAL.